FROM registry.fedoraproject.org/fedora-minimal:41

USER 0:0

WORKDIR /opt

RUN /usr/bin/microdnf -y install unzip \
 && /usr/bin/curl -JLOk https://github.com/grafana/loki/releases/download/v2.9.11/loki-linux-amd64.zip \
 && /usr/bin/curl -JLOk https://github.com/grafana/loki/releases/download/v2.9.11/promtail-linux-amd64.zip \
 && /usr/bin/unzip loki-linux-amd64.zip \
 && /usr/bin/unzip promtail-linux-amd64.zip \
 && /usr/bin/mkdir -m 0770 -p /opt/loki/bin \
 && /usr/bin/mv loki-linux-amd64 /opt/loki/bin/loki \
 && /usr/bin/mv promtail-linux-amd64 /opt/loki/bin/promtail \
 && /usr/bin/mkdir -m 0770 -p /var/log/loki \
 && /usr/bin/mkdir -m 0770 -p /srv/loki/data

COPY --chmod=0640 loki.yaml /etc/opt/

USER 1000:0

EXPOSE 3100

VOLUME /srv/loki/data

ENTRYPOINT [ "/opt/loki/bin/loki", "--config.file=/etc/opt/loki.yaml" ]