FROM registry.fedoraproject.org/fedora-minimal:41

USER 0:0

WORKDIR /opt

RUN /usr/bin/microdnf -y install tar gzip \
 && /usr/bin/curl -JLOk https://dl.grafana.com/oss/release/grafana-11.4.0.linux-amd64.tar.gz \
 && /usr/bin/tar -xzf grafana-11.4.0.linux-amd64.tar.gz \
 && /usr/bin/ln -s grafana-v11.4.0 grafana \
 && /usr/bin/mkdir -m 0770 -p /var/log/grafana \
 && /usr/bin/mkdir -m 0770 -p /srv/grafana/data

COPY --chmod=0640 grafana.ini        /etc/opt/
COPY --chmod=0640 loki-ds.yaml       /etc/opt/grafana/provisioning/datasources/
COPY --chmod=0640 prometheus-ds.yaml /etc/opt/grafana/provisioning/datasources/

USER 1000:0

EXPOSE 3000

VOLUME /srv/grafana/data

ENTRYPOINT [ "/opt/grafana/bin/grafana", "server", "--config", "/etc/opt/grafana.ini", "--homepath", "/opt/grafana" ]