apiVersion: 1
datasources:
  - access: proxy
    editable: false
    isDefault: false
    name: Prometheus
    type: prometheus
    url: http://prometheus:9090
deleteDatasources:
  - name: Prometheus
prune: true