FROM registry.fedoraproject.org/fedora-minimal:41

USER 0:0

WORKDIR /opt

RUN /usr/bin/microdnf -y install tar gzip \
 && /usr/bin/curl -JLOk https://github.com/prometheus/prometheus/releases/download/v2.53.3/prometheus-2.53.3.linux-amd64.tar.gz \
 && /usr/bin/tar -xzf prometheus-2.53.3.linux-amd64.tar.gz \
 && /usr/bin/ln -s prometheus-2.53.3.linux-amd64 prometheus \
 && /usr/bin/mkdir -m 0770 -p /var/log/prometheus \
 && /usr/bin/mkdir -m 0770 -p /srv/prometheus/data

COPY --chmod=0640 application.yaml /etc/opt/
COPY --chmod=0640 prometheus.yaml  /etc/opt/

USER 1000:0

EXPOSE 9090

VOLUME /srv/prometheus/data

ENTRYPOINT [ "/opt/prometheus/prometheus", "--config.file", "/etc/opt/prometheus.yaml", "--storage.tsdb.path", "/srv/prometheus/data" ]